### ISSUE TITLE
Stucks at mozilla first run in windows. 

### ISSUE THREAD

**Issue by harshuljain13** [akul08/mci-scraper#2]
code stuck at initial step itself because of Mozilla first run.

![1](https://cloud.githubusercontent.com/assets/9362636/12197618/6f17c40c-b62e-11e5-9ffb-f2fd21e0843a.png)
![2](https://cloud.githubusercontent.com/assets/9362636/12197623/7a8ef008-b62e-11e5-94da-28e6eaf4dece.png)
![3](https://cloud.githubusercontent.com/assets/9362636/12197626/804afd8e-b62e-11e5-92d5-9a29414a6020.png)

**Comment by akul08** [comment]
Never tried it on Windows but it works perfectly in Linux. Try switching to Linux OS for better support.
